### ISSUE TITLE
Household Naming Consistency

### ISSUE THREAD

**Issue by Hare-J** [abaporu-C/GROW-POS#315] opened 2022-04-06 01:47 UTC
Remove the word "House" from in front of the household names entered in Seed Data, or enforce rules and guidance for users inputting a house so that **every** house is "House X". Make sure household names are made consistent. 

"Need to work on the way names are entered. All your seed data places the word “house’ in front of the last name. I entered one with just a last name. Need to work on enforcing consistency in the names. Provide guidance to the user. " - Dave Kendell

**Comment by samjwhite** [comment] 2022-04-10 20:56
duplicate of #314 fixed

**Closed by samjwhite** 2022-04-10 20:56 UTC
